license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="jaarm.png"
description='''
Just Another Angel Ring Mod adds a simple Angel Ring to the game for Minecraft 26.1.2+.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="curios"
    type="required"
    versionRange="[15.0.0-beta.2+26.1.2,)"
    ordering="NONE"
    side="BOTH"